Description of denoising_demo3
Home > src > main > matlab > denoising_demo3.m
denoising_demo3
PURPOSE
denoising_demo3
SYNOPSIS
This is a script file.
DESCRIPTION
 denoising_demo3
 Denoising example (geophysics data) and plot all wavelets
CROSS-REFERENCE INFORMATION
This function calls:
flaglet_axisym_analysis flaglet_axisym_analysis
flaglet_plot_f
gen_geomodel
This function is called by:
SOURCE CODE
% denoising_demo3
% Denoising example (geophysics data) and plot all wavelets
% Resolution parameters
L = 92 ;
P = 92 ;
R = 3000;
% Layout parameters
minbound = -2;
maxbound = 2;
zoomfactor = 2.2;
% Generates geophysics data on the ball
f_ini = gen_geomodel(L, P);
disp('Analysis the signal (flag_analysis)...')
f_lmp = flag_analysis(f_ini, 'R', R, 'reality', true);
disp('Reconstruct the field (flag_synthesis)...')
f = flag_synthesis(f_lmp, 'R', R, 'reality', true);
% r = load('horizon_01_30k.mat');
% data = r.horizon_01_30k;
%
% if max(data(:,2)) > max(data(:,3))
%     temp = data;
%     data(:,3) = temp(:,2);
%     data(:,2) = temp(:,3);
% end
%
% R = 420;
%
% disp('Pixelise data...')
% f_ini = pixelizedeltas(data, L, P, R);
% disp('Flag_analysis...')
% f_lmp = flag_analysis(f_ini, 'R', R, 'reality', true);
% disp('Flag_synthesis...')
% f = flag_synthesis(f_lmp, 'R', R, 'reality', true);
% Wavelet decomposition parameters
Downsample = true;
B_l = 5 ;
B_p = 5 ;
J_min_l = 2 ;
J_min_p = 2 ;
J_l = ceil(log(L) ./ log(B_l));
J_p = ceil(log(P) ./ log(B_p));
disp('Compute tilling of harmonic space...')
[kappa kappa0] = flaglet_axisym_tilling(B_l, B_p, L, P, J_min_l, J_min_p);
disp('Find noise covariance from SNR')
SNR_ini = 8.0;
f_power = sum(sum(abs(f_lmp).^2));
noise_power = f_power * (10.0^(-SNR_ini/10.0));
factor = sum(((1:P)./P).^2) * L * L ;
sigma_noise = sqrt(noise_power / factor)
disp('Generate random noise n_lmp of std dev sigma')
n_lmp = sigma_noise * randn(P, L^2);
    for en = 1:P
      for el = 0:L-1
        ind = ssht_elm2ind(el, 0);
        n_lmp(en,ind) = sigma_noise .* randn * (en/P) ;
        for m = 1:el
          ind = ssht_elm2ind(el, m);
          n_lmp(en,ind) = ...
            sqrt(sigma_noise^2./2) .* randn * (en/P)  ...
            + sqrt(-1) * sqrt(sigma_noise^2./2) .* randn * (en/P)  ;
        end
      end
    end
noise_power = sum(sum(abs(n_lmp).^2));
SNR_before = 10*log10(f_power / noise_power)
disp('Construct the noise in real space...')
initial_noise = flag_synthesis(n_lmp, 'R', R, 'Reality', true);
disp('Add the noise to the initial dataset')
%g_lmp = f_lmp + n_lmp ;
g = f + initial_noise ;
disp('Perform wavelet decomposition of f...')
[f_wav, f_scal] = flaglet_axisym_analysis(f, 'B_l', B_l, 'B_p', B_p, 'L', L, 'P', P, 'J_min_l', J_min_l, 'J_min_p', J_min_p, 'Reality', true, 'Downsample', Downsample);
disp('Perform wavelet decomposition of g...')
[g_wav, g_scal] = flaglet_axisym_analysis(g, 'B_l', B_l, 'B_p', B_p, 'L', L, 'P', P, 'J_min_l', J_min_l, 'J_min_p', J_min_p, 'Reality', true, 'Downsample', Downsample);
% Layout parameters
minbound = -1.0;
maxbound = 1.0;
Lplot = 192;
Pplot = 192;
layer = 173;
zoomfactor = 2.0;
nx = 2;
ny = 2;
figure('Position',[100 100 1000 850])
ind = 1;
subplot(ny, nx, ind);
flaglet_plot_f(f, 'L', Lplot, 'P', Pplot, 'layer', layer)
zoom(zoomfactor)
caxis([minbound maxbound])
title('Data')
ind = 2;
subplot(ny, nx, ind);
flaglet_plot_f(g, 'L', Lplot, 'P', Pplot, 'layer', layer)
zoom(zoomfactor)
caxis([minbound maxbound])
title('Noisy data')
ind = 3;
subplot(ny, nx, ind);
flaglet_plot_f(f_scal, 'L', Lplot, 'P', Pplot, 'layer', layer)
zoom(zoomfactor)
caxis([minbound maxbound])
title('Data')
ind = 4;
subplot(ny, nx, ind);
flaglet_plot_f(g_scal, 'L', Lplot, 'P', Pplot, 'layer', layer)
zoom(zoomfactor)
caxis([minbound maxbound])
title('Noisy data')
nx = 2;
ny = 4;
J_l = [ 1 2 ];
J_n = [ 1 2 ];
figure('Position',[100 100 1000 1200])
ind = 0;
for jl = J_l
    for jn = J_n
        ind = ind + 1;
        subplot(ny, nx, ind);
        flaglet_plot_f( f_wav{jl, jn}, 'L', Lplot, 'P', Pplot, 'layer', layer )
        zoom(zoomfactor)
        title(['F : jl=',int2str(jl),' jn=',int2str(jn)])
        caxis([minbound maxbound])
        ind = ind + 1;
        subplot(ny, nx, ind);
        flaglet_plot_f( g_wav{jl, jn}, 'L', Lplot, 'P', Pplot, 'layer', layer )
        zoom(zoomfactor)
        title(['G : jl=',int2str(jl),' jn=',int2str(jn)])
        caxis([minbound maxbound])
    end
end